spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: wsl:8848
  profiles:
    active: app1

management:
  endpoints:
    web:
      exposure:
        include: '*'
