spring:
  profiles:
    active: app1
  application:
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://wsl:3306/db2019?useSSL=false
      username: root
      password: PIom0163

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://local1:7001/eureka,http://local2:7002/eureka
  instance:
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

logging:
  level:
    root: info
    org.apache.tomcat.util.net: warn